### ISSUE TITLE
swan proxy 重构和增强

### ISSUE THREAD

**Issue by bbklab** [Dataman-Cloud/swan#662]
- [x] 会话保持，1h过期   #661  #731 
- [x] 数据统计， 全局/应用 的 请求数(累积/实时)，进出流量(累积/实时)，在线连接数。 #661
- [x] 外网访问，自定义访问域名方式  #661
- [x] upstream 运行时的查看更新删除  #661
- [x] http / https proxy  
  - [x] 常规http应答，websocket，event stream 的转发  #661
  - [x] 在proxy上配置统一证书， 为后端 http 服务的访问 提供 加密传输  #661
  - [x] 后端本身就是 https 服务的转发  #661
- [ ] L4 proxy
  - [x] tcp  #661 
  - [ ] udp
- [x] API / Docs #661 
- [x] 压力测试，对比nginx
- [x] 创建proxy代理改为scheduler 调用的同步方式，不再用event方式 #726

**Comment by xiaods** [comment]
udp可以不做。
